2025-05-23 16:37:10,937 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: None
2025-05-23 16:37:10,956 - main1.py:[55] - [ERROR] - 生成测试报告时出错: Command '['allure', 'generate', './allure-results', '-o', 'allure-report/fa95384c', '--clean']' returned non-zero exit status 1.
2025-05-23 16:37:10,956 - main1.py:[198] - [WARNING] - 测试报告生成失败，跳过钉钉通知和邮件发送。
2025-05-23 16:37:46,792 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: None
2025-05-23 16:37:46,813 - main1.py:[55] - [ERROR] - 生成测试报告时出错: Command '['allure', 'generate', './allure-results', '-o', 'allure-report/7b897c97', '--clean']' returned non-zero exit status 1.
2025-05-23 16:37:46,815 - main1.py:[198] - [WARNING] - 测试报告生成失败，跳过钉钉通知和邮件发送。
2025-05-23 16:38:45,866 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 'pytest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

2025-05-23 16:38:45,889 - main1.py:[63] - [ERROR] - 生成测试报告时出错: Command '['C:\\Program Files\x07llure-2.25.0\x08in\x07llure.bat', 'generate', './allure-results', '-o', 'allure-report/b3c19bc4', '--clean']' returned non-zero exit status 1.
2025-05-23 16:38:45,889 - main1.py:[206] - [WARNING] - 测试报告生成失败，跳过钉钉通知和邮件发送。
2025-05-23 16:39:50,329 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 'pytest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

2025-05-23 16:39:50,352 - main1.py:[63] - [ERROR] - 生成测试报告时出错: Command '['C:\\Program Files\x07llure-2.25.0\x08in\x07llure.bat', 'generate', './allure-results', '-o', 'allure-report/6d76a2c5', '--clean']' returned non-zero exit status 1.
2025-05-23 16:39:50,352 - main1.py:[206] - [WARNING] - 测试报告生成失败，跳过钉钉通知和邮件发送。
2025-05-23 16:41:40,676 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 'pytest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

2025-05-23 16:41:40,695 - main1.py:[63] - [ERROR] - 生成测试报告时出错: Command '['D:\x07llure-2.33.0\x08in\x07llure.bat', 'generate', './allure-results', '-o', 'allure-report/64375c3e', '--clean']' returned non-zero exit status 1.
2025-05-23 16:41:40,695 - main1.py:[206] - [WARNING] - 测试报告生成失败，跳过钉钉通知和邮件发送。
2025-05-23 16:44:16,142 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 'pytest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

2025-05-23 16:50:50,781 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 16:51:03,479 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 16:53:49,791 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 16:55:03,851 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 17:06:52,368 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 17:08:04,484 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir=./allure-results
  inifile: D:\AutomationResearch\apiAutomationRH\pytest.ini
  rootdir: D:\AutomationResearch\apiAutomationRH


2025-05-23 17:14:43,277 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: file or directory not found: D:\\apiAutomationRH\\TestCase


2025-05-23 17:19:46,823 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:22:21,676 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:23:14,251 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:23:18,877 - main1.py:[208] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:23:18,877 - main1.py:[141] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:23:21,890 - main1.py:[160] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:23:23,920 - main1.py:[187] - [INFO] - 邮件发送成功
2025-05-23 17:23:32,041 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:23:34,855 - main1.py:[208] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:23:34,856 - main1.py:[141] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:23:37,867 - main1.py:[160] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:23:39,257 - main1.py:[187] - [INFO] - 邮件发送成功
2025-05-23 17:26:09,948 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:26:13,200 - main1.py:[208] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:26:13,200 - main1.py:[141] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:26:16,212 - main1.py:[160] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:26:18,129 - main1.py:[187] - [INFO] - 邮件发送成功
2025-05-23 17:29:20,260 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: ERROR: file or directory not found: D:\\apiAutomationRH\\TestCase\\test_login.py


2025-05-23 17:29:23,743 - main1.py:[208] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:29:23,744 - main1.py:[141] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:29:26,753 - main1.py:[160] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:29:28,112 - main1.py:[187] - [INFO] - 邮件发送成功
2025-05-23 17:31:50,906 - main1.py:[40] - [ERROR] - 测试执行失败，错误信息: 
2025-05-23 17:31:53,750 - main1.py:[208] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:31:53,750 - main1.py:[141] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:31:56,762 - main1.py:[160] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:31:58,134 - main1.py:[187] - [INFO] - 邮件发送成功
2025-05-23 17:35:49,486 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc3NDgsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.kgxzRvVNI69jMJ7ajYY4REs-ZMkSeOcv73-Q9P2QlRk'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:35:49,487 - test_process_related.py:[25] - [INFO] - 本用例正在执行：test_storeProcessInfoData01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:35:50,692 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc3NDksImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.JAbsHB5_fWnsDOpA-O15b87WpE5SVOg9F7tvo82TLCo'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:35:50,692 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc3NDksImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.JAbsHB5_fWnsDOpA-O15b87WpE5SVOg9F7tvo82TLCo'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:35:50,693 - test_process_related.py:[42] - [INFO] - 本用例正在执行：test_storeProcessInfoData02。获取到的结果是：已有重复数据录入!, 期望的结果是: 已有重复数据录入!
2025-05-23 17:35:51,883 - test_process_related.py:[58] - [INFO] - 本用例正在执行：test_removeProcessInfoData01。获取到的结果是：数据删除成功, 期望的结果是: 数据删除成功
2025-05-23 17:35:53,167 - delete_data.py:[23] - [INFO] - 物料数据删除成功
2025-05-23 17:35:54,505 - test_product_materials.py:[28] - [INFO] - 本用例正在执行：test_productaterials01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:35:55,764 - test_product_materials.py:[45] - [INFO] - 本用例正在执行：test_productaterials02。获取到的结果是：已有重复数据录入!, 期望的结果是:已有重复数据录入!
2025-05-23 17:35:57,252 - test_product_materials.py:[61] - [INFO] - 本用例正在执行：test_getMaterialInfoAutoQueryDatas01。获取到的结果是：获取数据成功！, 期望的结果是: 获取数据成功！
2025-05-23 17:35:58,516 - test_product_materials.py:[78] - [INFO] - 本用例正在执行：test_removeMaterialInfoData01。获取到的结果是：数据删除成功, 期望的结果是: 获取数据成功！
2025-05-23 17:36:01,409 - test_product_materials.py:[96] - [INFO] - 本用例正在执行：test_storeManufactureBomData01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:36:02,924 - test_product_materials.py:[130] - [INFO] - 本用例正在执行：test_getGetBomMasterViewAutoQueryDatas01。获取到的结果是：获取数据成功！, 期望的结果是:获取数据成功！
2025-05-23 17:36:05,469 - test_product_materials.py:[147] - [INFO] - 本用例正在执行：test_gremoveManufactureBomData01。获取到的结果是：数据删除成功, 数据删除成功
2025-05-23 17:36:06,760 - delete_data.py:[23] - [INFO] - 物料数据删除成功
2025-05-23 17:36:06,927 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-23 17:36:06,927 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-23 17:36:07,119 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:36:07,119 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:36:07,119 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:36:07,139 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:36:07,139 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:36:07,139 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:36:07,139 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:36:11,181 - main1.py:[214] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:36:11,182 - main1.py:[147] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:36:14,195 - main1.py:[166] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:36:15,506 - main1.py:[193] - [INFO] - 邮件发送成功
2025-05-23 17:39:07,224 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc5NDYsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.0jODHdgUy2o4TPO8UOOSV1VpaaksD5lMB4Ya9c-V3Eg'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:39:07,224 - test_process_related.py:[25] - [INFO] - 本用例正在执行：test_storeProcessInfoData01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:39:08,403 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc5NDcsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9._Gia3TXWWzmI6j3vRNSPk0kYkOU8Lmfbg3YiYJWDSPk'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:39:08,403 - production_process.py:[33] - [INFO] - 当前执行新增工序接口：storeProcessInfoData，
请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，
请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDg1OTc5NDcsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9._Gia3TXWWzmI6j3vRNSPk0kYkOU8Lmfbg3YiYJWDSPk'}，
请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01'}
2025-05-23 17:39:08,404 - test_process_related.py:[42] - [INFO] - 本用例正在执行：test_storeProcessInfoData02。获取到的结果是：已有重复数据录入!, 期望的结果是: 已有重复数据录入!
2025-05-23 17:39:09,568 - test_process_related.py:[58] - [INFO] - 本用例正在执行：test_removeProcessInfoData01。获取到的结果是：数据删除成功, 期望的结果是: 数据删除成功
2025-05-23 17:39:10,994 - delete_data.py:[23] - [INFO] - 物料数据删除成功
2025-05-23 17:39:12,209 - test_product_materials.py:[28] - [INFO] - 本用例正在执行：test_productaterials01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:39:13,434 - test_product_materials.py:[45] - [INFO] - 本用例正在执行：test_productaterials02。获取到的结果是：已有重复数据录入!, 期望的结果是:已有重复数据录入!
2025-05-23 17:39:14,709 - test_product_materials.py:[61] - [INFO] - 本用例正在执行：test_getMaterialInfoAutoQueryDatas01。获取到的结果是：获取数据成功！, 期望的结果是: 获取数据成功！
2025-05-23 17:39:16,073 - test_product_materials.py:[78] - [INFO] - 本用例正在执行：test_removeMaterialInfoData01。获取到的结果是：数据删除成功, 期望的结果是: 获取数据成功！
2025-05-23 17:39:18,490 - test_product_materials.py:[96] - [INFO] - 本用例正在执行：test_storeManufactureBomData01。获取到的结果是：数据新增成功, 期望的结果是: 数据新增成功
2025-05-23 17:39:19,829 - test_product_materials.py:[130] - [INFO] - 本用例正在执行：test_getGetBomMasterViewAutoQueryDatas01。获取到的结果是：获取数据成功！, 期望的结果是:获取数据成功！
2025-05-23 17:39:22,336 - test_product_materials.py:[147] - [INFO] - 本用例正在执行：test_gremoveManufactureBomData01。获取到的结果是：数据删除成功, 数据删除成功
2025-05-23 17:39:23,552 - delete_data.py:[23] - [INFO] - 物料数据删除成功
2025-05-23 17:39:23,720 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-23 17:39:23,720 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-23 17:39:23,905 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:39:23,905 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:39:23,905 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-23 17:39:23,922 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:39:23,922 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:39:23,922 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:39:23,922 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-23 17:39:27,495 - main1.py:[215] - [INFO] - 钉钉发送状态码: 200
2025-05-23 17:39:27,496 - main1.py:[148] - [INFO] - 端口 8000 可用，尝试启动服务器...
2025-05-23 17:39:30,506 - main1.py:[167] - [INFO] - 端口 8000 可连接，生成报告链接...
2025-05-23 17:39:33,244 - main1.py:[194] - [INFO] - 邮件发送成功
