ERROR    ProcessRelated:production_process.py:56 请求发生错误: HTTPConnectionPool(host='192.168.0.135', port=8282): Max retries exceeded with url: /ProductRouteApi/StoreProcessInfoData (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026368303810>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))，请求 URL: http://192.168.0.135:8282/ProductRouteApi/StoreProcessInfoData，请求头: {'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxNTAiLCJVc2VyQ29kZSI6IkRlbW9BZG1pbiIsIlVzZXJOYW1lIjoiRGVtb0FkbWluIiwiVXNlclR5cGUiOiIxIiwiQ29tcGFueUNvZGUiOiIwMDAwMCIsIkZhY3RvcnlDb2RlIjoiMDAwMDAuMDAwMDEiLCJJcCI6IjE5Mi4xNjguODIuMjA0IiwiT3JnYW5pemF0aW9uU3RydWN0dXJlQ29kZSI6IjAwMDAwLjAwMDAxLjAwMDAzIiwiZXhwIjoxNzUyNDU5OTEyLCJpc3MiOiJSaC5NZXMiLCJhdWQiOiJSaC5NZXMuU2VydmljZXMifQ.zZpQHiCVyQyFY8E8H8lngnqtWsf4NNN6Kmq3ycFFQtU'}，请求体: {'ProcessCode': 'Automation01', 'ProcessName': '自动化测试工序01', 'ProcessDescription': '', 'EquipmentCode': None, 'ProcessDisplayName': '', 'IsReportCheck': False, 'IsOutSide': False, 'IsExportFlowCard': False, 'IsUsePackingList': False, 'IsPatrolInspect': False, 'IsFirstInspect': True, 'IsFinishInspect': False, 'IsBindDispatchCode': False, 'IsKeyComponent': False, 'IsKittingCheck': False, 'IsProcessAudit': False, 'IsOutsourcing': False, 'SupplierCode': None, 'SupplierName': '', 'Remark': '', 'OpSign': 1, 'CompanyCode': '00000', 'FactoryCode': '00000.00001'}
ERROR    mainprocess_tests:test_mainprocess.py:188 新增工序失败：storeProcessInfoData接口返回None，请检查接口或依赖服务是否正常
assert None is not None